[package]
name = "day1_part2_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
advent_of_code = { path = "../../../advent_of_code" }
anyhow = { version = "1.0.94", features = ["backtrace"] }
day1_common_2024 = { path = "../common" }
dotenv = "0.15.0"
